---
# Site settings
baseurl: ""
description: "Whitney IT Pty Ltd"
email: "james@whitney.io"
title: "Whitney IT Pty Ltd"
url: "http://whitney.io"

# Build settings
encoding: "utf-8"
exclude:
    # Directories
    - "bower_components"
    - "build"
    - "coverage"
    - "dist"
    - "docs"
    - "lib"
    - "node_modules"
    - "plato"
    - "src"
    - "tests"
    # Files
    - "_config.yml"
    - "bower.json"
    - "CNAME"
    - "gulpfile.js"
    - "karma.conf.js"
    - "LICENSE.md"
    - "npm-debug.log"
    - "package.json"
    - "README.md"
lsi: false
port: 3333
safe: true
timezone: "Australia/Sydney"
